"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const {buildDungeonMultiReward}=require("./dungeonMultiReward");

function room(){return{dungeonSolo:true,dungeonMulti:true,combatVersion:2,status:"victory",expeditionDifficulty:1,expeditionRoomType:"monster",multiFamily:"ghost",multiTier:1,monster:{id:"ghost_t1_normal_a",family:"ghost"},members:{m1:{}},encounter:{primaryTargetId:"primary"},targetOrder:["primary","add_1","add_2"],targets:{primary:{id:"ghost_t1_normal_a",instanceId:"primary",currentHp:0,alive:false},add_1:{id:"ghost_1",instanceId:"add_1",currentHp:0,alive:false},add_2:{id:"ghost_t1_normal_b",instanceId:"add_2",currentHp:0,alive:false}}};}

test("solo dungeon multi derives per-target material/card and one tile envelope",()=>{const reward=buildDungeonMultiReward({room:room(),battleId:"b1",memberId:"m1"});assert.equal(reward.targetInstanceIds.length,3);assert.equal(reward.chests.length,3);assert.ok(Object.values(reward.materialTotals).reduce((a,b)=>a+b,0)>=3);assert.ok(reward.coins>0);assert.ok(reward.archerXP>0);assert.match(reward.claimId,/dungeon_multi_solo/);});
test("reward is deterministic for an idempotent claim replay",()=>{const input={room:room(),battleId:"b1",memberId:"m1"};assert.deepEqual(buildDungeonMultiReward(input),buildDungeonMultiReward(input));});
test("fails closed without terminal v2 room proof",()=>{assert.throws(()=>buildDungeonMultiReward({room:{...room(),status:"active"},battleId:"b1",memberId:"m1"}),/not_terminal/);});
test("rejects forged catalog roles, family, tier and primary identity",()=>{const base=room();assert.throws(()=>buildDungeonMultiReward({room:{...base,targets:{...base.targets,add_1:{...base.targets.add_1,id:"ghost_t1_boss"}}},battleId:"b1",memberId:"m1"}),/target_role_invalid/);assert.throws(()=>buildDungeonMultiReward({room:{...base,multiFamily:"mountain"},battleId:"b1",memberId:"m1"}),/catalog_mismatch/);assert.throws(()=>buildDungeonMultiReward({room:{...base,multiTier:2},battleId:"b1",memberId:"m1"}),/catalog_mismatch/);assert.throws(()=>buildDungeonMultiReward({room:{...base,monster:{...base.monster,id:"ghost_1"}},battleId:"b1",memberId:"m1"}),/primary_mismatch/);});

test("elite dungeon multi accepts the normal catalog primary used by strong elite rooms",()=>{const base=room();const normalReward=buildDungeonMultiReward({room:base,battleId:"elite-role",memberId:"m1"});const eliteReward=buildDungeonMultiReward({room:{...base,expeditionRoomType:"elite"},battleId:"elite-role",memberId:"m1"});assert.equal(normalReward.archerXP,5);assert.equal(eliteReward.archerXP,8);assert.ok(eliteReward.coins>normalReward.coins);});

test("boss dungeon multi accepts either miniBoss or boss as the locked primary",()=>{const base=room();for(const primaryMonsterId of ["ghost_t1_mini_a","ghost_t1_boss"]){const bossRoom={...base,expeditionRoomType:"boss",monster:{...base.monster,id:primaryMonsterId},targets:{...base.targets,primary:{...base.targets.primary,id:primaryMonsterId}}};assert.doesNotThrow(()=>buildDungeonMultiReward({room:bossRoom,battleId:`boss-${primaryMonsterId}`,memberId:"m1"}));}});

test("normal rooms cannot forge a boss primary and boss rooms cannot forge a boss-class add",()=>{const base=room();const forgedNormalPrimary={...base,monster:{...base.monster,id:"ghost_t1_boss"},targets:{...base.targets,primary:{...base.targets.primary,id:"ghost_t1_boss"}}};assert.throws(()=>buildDungeonMultiReward({room:forgedNormalPrimary,battleId:"forged-primary",memberId:"m1"}),/target_role_invalid/);const forgedBossAdd={...base,expeditionRoomType:"boss",monster:{...base.monster,id:"ghost_t1_boss"},targets:{...base.targets,primary:{...base.targets.primary,id:"ghost_t1_boss"},add_1:{...base.targets.add_1,id:"ghost_t1_mini_a"}}};assert.throws(()=>buildDungeonMultiReward({room:forgedBossAdd,battleId:"forged-add",memberId:"m1"}),/target_role_invalid/);});
