"use strict";
const test=require("node:test");
const assert=require("node:assert/strict");
const {SUPPORTED_EFFECTS,startPatch,submissionPatch,submissionReplayStatus,resolveRound,validateSnapshot}=require("./multiMonsterPartyV2");

function member(over={}){return{hp:1,catId:"niuniu",catATK:25,loadoutSnapshot:{version:2,baseStats:{hp:200,atk:30,def:10},cards:{effectVersion:2,supportedEffects:[...SUPPORTED_EFFECTS],unsupportedEffectKeys:[],familyDamageBonusPct:{ghost:10},familyDamageReducePct:{ghost:5}}},...over};}
function waiting(over={}){return{huntType:"multi",multiMonster:true,status:"waiting",hostId:"p1",multiFamily:"ghost",multiTier:1,arrowsPerRound:3,members:{p1:member()},...over};}

test("start creates a deterministic v2 encounter and freezes snapshot totals",()=>{const a=startPatch(waiting(),"r1"),b=startPatch(waiting(),"r1");assert.deepEqual(a,b);assert.equal(a.members.p1.hp,200);assert.equal(a.combatVersion,2);assert.equal(a.roundPhase,"input");});
test("dungeon start preserves the persisted encounter identity and targets",()=>{const encounter={kind:"multi",encounterId:"dungeon:run:0:r1",targets:[0,1,2].map(i=>({id:`ghost_${i}`,instanceId:i?`add_${i}`:"primary",name:`m${i}`,family:"ghost",hp:100,maxHp:100,currentHp:100,atk:10,def:5,alive:true,encounter:i?"normal":"boss"}))};const patch=startPatch({...waiting(),huntType:undefined,multiMonster:undefined,dungeonMulti:true,expeditionMode:true,encounter},"battle-room");assert.deepEqual(patch.targetOrder,["primary","add_1","add_2"]);assert.equal(patch.targets.primary.id,"ghost_0");assert.equal(patch.targets.add_2.currentHp,100);});
test("dungeon start preserves run HP and locked expedition combat stats",()=>{const source=waiting({dungeonMulti:true,expeditionMode:true,huntType:undefined,multiMonster:undefined,encounter:{kind:"multi",targets:[0,1,2].map(i=>({id:`ghost_${i}`,instanceId:i?`add_${i}`:"primary",hp:100,currentHp:100,atk:10,def:5}))}});source.members.p1={...source.members.p1,hp:37,maxHP:150,atk:77,def:44,alive:true};const patch=startPatch(source,"dungeon-room");assert.equal(patch.members.p1.hp,37);assert.equal(patch.members.p1.maxHP,150);assert.equal(patch.members.p1.loadoutSnapshot.baseStats.atk,77);assert.equal(patch.members.p1.loadoutSnapshot.baseStats.def,44);});
test("unsupported structured effects fail closed",()=>{const bad=member();bad.loadoutSnapshot.cards.unsupportedEffectKeys=["worldboss_unknown"];assert.throws(()=>validateSnapshot(bad),/unsupported_loadout_effect/);});
test("the full v2 effect declaration is accepted",()=>{const value=member();value.loadoutSnapshot.cards.supportedEffects=["status_inflict","opening_shield","reflect","end_round_heal","cat_archetype","cat_bond"];assert.equal(validateSnapshot(value).version,2);});
test("submission revision is monotonic and forged revision is ignored",()=>{const room={...startPatch(waiting(),"r1"),status:"active"};const one=submissionPatch(room,"r1","p1",{round:1,arrows:["10","9","M"],attackMode:"focus",targetId:"monster_0",revision:99});room.members.p1.submission=one;const two=submissionPatch(room,"r1","p1",{round:1,arrows:["10","9","M"],attackMode:"focus",targetId:"monster_0",revision:1});assert.equal(one.revision,1);assert.equal(two.revision,2);});
test("resolution is deterministic, id-addressable and clears submissions",()=>{const room={...startPatch(waiting(),"r1"),id:"r1",status:"active"};room.members.p1.submission=submissionPatch(room,"r1","p1",{round:1,arrows:["10","10","10"],attackMode:"focus",targetId:"monster_0"});room.members.p1.ready=true;const a=resolveRound(room,"r1"),b=resolveRound(room,"r1");assert.deepEqual(a,b);assert.ok(a.lastResolution.events.every(event=>event.id));assert.ok(Number(a.lastResolution.targetHpBefore.monster_0)>Number(a.targets.monster_0.currentHp));assert.equal(a.lastResolution.memberHpBefore.p1,room.members.p1.hp);assert.equal(a.members.p1.submission,null);assert.equal(a.members.p1.ready,false);assert.equal(a.lastResolution.events.filter(e=>e.type==="cat_action").length,1);});
test("resolution records submitted member ids for replay acknowledgement",()=>{const room={...startPatch(waiting(),"r-replay"),status:"active"};room.members.p1.submission=submissionPatch(room,"r-replay","p1",{round:1,arrows:["10","10","10"],attackMode:"focus",targetId:"monster_0"});room.members.p1.ready=true;const resolved=resolveRound(room,"r-replay");assert.deepEqual(resolved.lastResolution.submittedIds,["p1"]);assert.deepEqual(submissionReplayStatus(resolved,"p1",{round:1}),{duplicate:true,alreadyResolved:true,resolutionId:"r-replay:1"});});
test("same-round duplicate submission is acknowledged without creating a revision",()=>{const room={...startPatch(waiting(),"r-dupe"),status:"active"};room.members.p1.submission=submissionPatch(room,"r-dupe","p1",{round:1,arrows:["10","9","8"],attackMode:"focus",targetId:"monster_0"});room.members.p1.ready=true;assert.deepEqual(submissionReplayStatus(room,"p1",{round:1}),{duplicate:true,alreadyResolved:false,revision:1});assert.equal(submissionReplayStatus(room,"p1",{round:2}),null);});
test("resolved dungeon participation increments validRounds for boss eligibility",()=>{const room={...startPatch(waiting(),"r1"),status:"active"};room.members.p1.submission=submissionPatch(room,"r1","p1",{round:1,arrows:["M","M","M"],attackMode:"focus",targetId:"monster_0"});room.members.p1.ready=true;assert.equal(resolveRound(room,"r1").members.p1.validRounds,1);});
test("locked and stale submissions are rejected",()=>{const room={...startPatch(waiting(),"r1"),status:"active",roundPhase:"resolving"};assert.throws(()=>submissionPatch(room,"r1","p1",{round:1,arrows:["10","10","10"],targetId:"monster_0"}),/round_locked/);});
test("status talents require their configured high-quality score",()=>{const low=waiting();low.members.p1.loadoutSnapshot.cards.combatMods={inflict:{poison:{chancePct:100,strength:2,duration:2,minScore:9}}};const room={...startPatch(low,"r-status"),status:"active"};room.members.p1.submission=submissionPatch(room,"r-status","p1",{round:1,arrows:["8","8","8"],attackMode:"focus",targetId:"monster_0"});room.members.p1.ready=true;const resolved=resolveRound(room,"r-status");assert.equal(resolved.lastResolution.events.some(event=>event.type==="status_applied"),false);});
test("guard specialization only reduces counters below its HP threshold",()=>{const source=waiting();source.members.p1.loadoutSnapshot.cards.combatMods={guardReductionPct:50,guardThresholdPct:35};const base={...startPatch(source,"r-guard"),status:"active"};const make=hp=>{const room=structuredClone(base);room.members.p1.hp=hp;room.members.p1.submission=submissionPatch(room,"r-guard","p1",{round:1,arrows:["M","M","M"],attackMode:"focus",targetId:"monster_0"});room.members.p1.ready=true;return resolveRound(room,"r-guard").lastResolution.events.find(event=>event.type==="monster_counter").amount;};assert.ok(make(60)<make(200));});
