import React from "react";

export default function HuntBattleReport({ won=true, monster, stats={}, receipt, partyMembers=[], onBack, onToggleDetails, detailsOpen=false, children }) {
  return <main data-hunt-battle-report="true" data-hunt-art="report-camp" style={{minHeight:"100vh",maxWidth:540,margin:"0 auto",padding:"18px 14px 28px",color:"#eaf2ff",backgroundColor:"#060a12",backgroundImage:"linear-gradient(180deg,rgba(4,9,20,.52),rgba(4,9,20,.86) 52%,rgba(4,9,20,.96)),url('/ui/hunt/hunt-report-camp-v1.webp')",backgroundPosition:"center top",backgroundRepeat:"no-repeat",backgroundSize:"cover"}}>
    <header style={{textAlign:"center",padding:"18px 12px",borderRadius:22,background:won?"linear-gradient(180deg,rgba(34,197,94,.16),rgba(15,23,42,.82))":"linear-gradient(180deg,rgba(239,68,68,.16),rgba(15,23,42,.82))",border:`1px solid ${won?"rgba(74,222,128,.35)":"rgba(248,113,113,.35)"}`}}><div style={{fontSize:38}}>{won?"🏆":"💀"}</div><div style={{fontSize:22,fontWeight:950,color:won?"#86efac":"#fca5a5"}}>{won?"狩獵成功":"狩獵失敗"}</div><div style={{fontSize:13,color:"#cbd5e1",marginTop:5}}>{monster?.icon} {monster?.name || "狩獵目標"}</div></header>
    <section style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:7,marginTop:12}}>{[["總分",stats.totalScore||0],["平均",Number(stats.avgScore||0).toFixed(1)],["命中率",`${Math.round((Number(stats.hitRate)||0)*100)}%`],["射箭評價",stats.grade||"E"],["評分",stats.performanceScore||0],["造成傷害",stats.dmgDealt||0],["回合",stats.roundCount||0],["箭數",stats.arrowCount||0]].map(([label,value])=><div key={label} style={{padding:"10px 5px",textAlign:"center",borderRadius:13,background:"rgba(255,255,255,.065)",border:"1px solid rgba(255,255,255,.09)"}}><div style={{fontSize:9,color:"#94a3b8"}}>{label}</div><div style={{fontSize:17,fontWeight:900,color:label==="射箭評價"?"#86efac":"#fcd34d",marginTop:2}}>{typeof value==="number"?value.toLocaleString():value}</div></div>)}</section>
    {partyMembers.length>0&&<section style={{marginTop:14,padding:12,borderRadius:16,background:"rgba(255,255,255,.04)"}}><div style={{fontSize:11,fontWeight:900,color:"#7dd3fc",marginBottom:8}}>隊伍貢獻</div>{partyMembers.map(member=><div key={member.id} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",fontSize:12,borderBottom:"1px solid rgba(255,255,255,.06)"}}><span>{member.name}</span><b style={{color:"#fca5a5"}}>{Number(member.dmgDealt||0).toLocaleString()} 傷害</b></div>)}</section>}
    <section style={{marginTop:14,padding:13,borderRadius:16,background:"rgba(15,23,42,.84)",border:"1px solid rgba(251,191,36,.22)"}}><div style={{fontSize:12,fontWeight:900,color:"#fcd34d",marginBottom:9}}>戰利品收據</div>{!won?<div style={{fontSize:12,color:"#94a3b8"}}>本場未獲得狩獵獎勵</div>:receipt?.status!=="confirmed"?<div style={{padding:"15px 6px",textAlign:"center",fontSize:12,color:"#bae6fd"}}>⏳ 獎勵同步中，系統會自動重試</div>:<><div style={{display:"grid",gap:7}}>{receipt.items.map(item=><div key={`${item.kind}-${item.id}-${item.tier||""}`} style={{display:"flex",gap:9,alignItems:"center",padding:"9px",borderRadius:11,background:"rgba(255,255,255,.05)"}}><span style={{fontSize:20}}>{item.icon}</span><span style={{flex:1,fontSize:12,fontWeight:800}}>{item.name}</span><b style={{color:"#fde68a"}}>×{item.quantity}</b></div>)}</div>{receipt.progression.map(item=><div key={item.kind} style={{display:"flex",justifyContent:"space-between",fontSize:12,paddingTop:8}}><span>{item.icon} {item.name}</span><b style={{color:"#c4b5fd"}}>+{item.amount}</b></div>)}{receipt.items.length===0&&receipt.progression.length===0&&<div style={{fontSize:12,color:"#94a3b8"}}>本場沒有額外掉落</div>}</>}</section>
    {children&&<section style={{marginTop:12}}>{detailsOpen&&children}<button type="button" onClick={onToggleDetails} style={{width:"100%",marginTop:8,padding:10,borderRadius:12,border:"1px solid rgba(148,163,184,.2)",background:"rgba(255,255,255,.04)",color:"#cbd5e1",fontWeight:800}}>{detailsOpen?"收起詳細紀錄":"查看詳細紀錄"}</button></section>}
    <button type="button" onClick={onBack} style={{width:"100%",marginTop:16,padding:13,border:0,borderRadius:14,background:"linear-gradient(135deg,#f7c65a,#e79a1e)",color:"#2d1b00",fontSize:15,fontWeight:950}}>返回狩獵</button>
  </main>;
}
