import { useEffect, useState } from "react";
import { previewGuestReview, submitGuestReviewByToken } from "../lib/guestReviewDb";

export default function GuestReviewPage({ token }) {
  const [status,setStatus]=useState("loading"),[rating,setRating]=useState(0),[message,setMessage]=useState(""),[consent,setConsent]=useState(false),[alias,setAlias]=useState(""),[error,setError]=useState(""),[googleUrl,setGoogleUrl]=useState("");
  useEffect(()=>{previewGuestReview(token).then(()=>setStatus("form")).catch(e=>{setError(e?.message||"連結無效或已過期");setStatus("error");});},[token]);
  const submit=async e=>{e.preventDefault();setError("");if(!rating)return setError("請選擇 1～5 星");if(consent&&!alias.trim())return setError("同意公開時請填寫匿名名稱");setStatus("sending");try{const result=await submitGuestReviewByToken(token,{rating,message,consentToPublish:consent,publicAlias:alias});setGoogleUrl(result.googleReviewUrl||"");setStatus("done");}catch(err){setError(err?.message||"送出失敗，請稍後再試");setStatus("form");}};
  return <main className="min-h-screen bg-slate-950 px-5 py-10 text-slate-100"><section className="mx-auto max-w-lg rounded-3xl border border-amber-400/20 bg-slate-900 p-6 shadow-2xl"><div className="text-4xl">🐈🏹</div><h1 className="mt-3 text-2xl font-black">分享這次射箭體驗</h1><p className="mt-2 text-sm leading-6 text-slate-400">評價送出後無法修改。若同意公開，會先經過貓小隊審核。</p>
    {status==="loading"&&<p className="mt-8">正在確認邀請連結…</p>}{status==="error"&&<p role="alert" className="mt-6 rounded-xl bg-red-950 p-4 text-red-200">{error}</p>}{status==="done"&&<div className="mt-8"><h2 className="text-xl font-black">謝謝你的回饋！</h2><p className="mt-2 text-slate-300">我們已收到這次評價。</p>{googleUrl&&<a href={googleUrl} target="_blank" rel="noreferrer" className="mt-6 block rounded-xl bg-amber-400 px-5 py-3 text-center font-black text-slate-950">也到 Google 分享體驗</a>}<p className="mt-3 text-xs text-slate-500">Google 評論需由你自行前往並送出。</p></div>}
    {(status==="form"||status==="sending")&&<form onSubmit={submit} className="mt-7 space-y-5"><fieldset><legend className="font-bold">整體評分</legend><div className="mt-2 flex gap-2" aria-label="整體評分">{[1,2,3,4,5].map(n=><button key={n} type="button" aria-label={`${n} 星`} aria-pressed={rating===n} onClick={()=>setRating(n)} className={`min-h-12 min-w-12 rounded-xl text-2xl ${n<=rating?"bg-amber-400 text-slate-950":"bg-slate-800"}`}>★</button>)}</div></fieldset><label className="block font-bold">留言<textarea required minLength={2} maxLength={1500} value={message} onChange={e=>setMessage(e.target.value)} className="mt-2 min-h-32 w-full rounded-xl bg-slate-800 p-3 font-normal" /></label><label className="flex gap-3 rounded-xl bg-slate-800 p-4"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>我同意經審核後將這則評價公開在貓小隊官網</span></label>{consent&&<label className="block font-bold">公開匿名名稱<input required maxLength={40} autoComplete="off" value={alias} onChange={e=>setAlias(e.target.value)} placeholder="例如：愛貓的弓箭新手" className="mt-2 min-h-12 w-full rounded-xl bg-slate-800 px-3 font-normal"/><small className="mt-2 block font-normal text-slate-400">不會自動使用你的註冊本名。</small></label>}{error&&<p role="alert" className="text-red-300">{error}</p>}<button disabled={status==="sending"} className="min-h-12 w-full rounded-xl bg-amber-400 font-black text-slate-950 disabled:opacity-50">{status==="sending"?"送出中…":"送出評價"}</button></form>}</section></main>;
}
