import { after, afterEach, before, test } from "node:test";
import { readFile } from "node:fs/promises";
import { assertFails, assertSucceeds, initializeTestEnvironment } from "@firebase/rules-unit-testing";
import { doc, getDoc, setDoc } from "firebase/firestore";
const PROJECT_ID="demo-catarrow";let env;const ADMIN="review-admin";
before(async()=>{env=await initializeTestEnvironment({projectId:PROJECT_ID,firestore:{rules:await readFile("firestore.rules","utf8")}});});afterEach(()=>env.clearFirestore());after(()=>env.cleanup());
async function seed(){await env.withSecurityRulesDisabled(async c=>{const db=c.firestore();await setDoc(doc(db,"admins",ADMIN),{active:true});await setDoc(doc(db,"guestReviewSubjects","member-secret"),{bookingId:"booking-secret",state:"scheduled"});await setDoc(doc(db,"guestReviews","member-secret"),{message:"private",email:"secret@example.test"});await setDoc(doc(db,"guestReviewConfig","main"),{enabled:false});await setDoc(doc(db,"publicGuestReviews","random-public-id"),{rating:5,message:"great",publicAlias:"Cat",approvedAt:new Date(),displayOrderAt:new Date()});});}
test("public can read only de-identified projection and cannot write it",async()=>{await seed();const db=env.unauthenticatedContext().firestore();await assertSucceeds(getDoc(doc(db,"publicGuestReviews","random-public-id")));await assertFails(setDoc(doc(db,"publicGuestReviews","forged"),{rating:5,message:"fake"}));for(const path of [["guestReviewSubjects","member-secret"],["guestReviews","member-secret"],["guestReviewConfig","main"]])await assertFails(getDoc(doc(db,...path)));});
test("guest cannot read or write internal review records",async()=>{await seed();const db=env.authenticatedContext("guest-uid",{email:"guest@example.test"}).firestore();await assertFails(getDoc(doc(db,"guestReviews","member-secret")));await assertFails(setDoc(doc(db,"guestReviews","member-secret"),{state:"approved"}));await assertFails(setDoc(doc(db,"guestReviewSubjects","member-secret"),{state:"submitted"}));});
test("admin can inspect internal records but all client writes remain denied",async()=>{await seed();const db=env.authenticatedContext(ADMIN).firestore();await assertSucceeds(getDoc(doc(db,"guestReviews","member-secret")));await assertSucceeds(getDoc(doc(db,"guestReviewSubjects","member-secret")));await assertSucceeds(getDoc(doc(db,"guestReviewConfig","main")));await assertFails(setDoc(doc(db,"guestReviews","member-secret"),{state:"approved"}));});
